//GET http://localhost:4004/odata/v4/product/printhelloworld(input='Hello')


//GET http://localhost:4004/odata/v4/productshop/Product


//GET http://localhost:4004/odata/v4/productshop/supplier

POST http://localhost:4004/odata/v4/productshop/Product
Content-Type: application/json

{
  "emission": 50000,
  "rating": "d",
  "name": "Pacifica",
  "Category": "MiniVan",
  "cost_price": 36457,
  "cost_stock": 2334
}